Update member_list.ejs
MyDataJapan/website pull request #36
Opened 2020-12-16 22:23 UTC by KesuikeTanabe

スマートシティ・インスティテュートのリンク先修正

2020-12-21 10:43 UTC, dixonsiu requested changes

2020-12-21 10:43 UTC, dixonsiu commented on _page/aboutus/member_list.ejs
> +                                            <a href="http://sci-japan.or.jp/" class="column" target="_blank">
```suggestion
                                            <a href="https://sci-japan.or.jp/" class="column" target="_blank">
```

2020-12-21 10:43 UTC, dixonsiu commented on _page/aboutus/member_list.ejs
> +                                            <a href="http://sci-japan.or.jp/" class="column" target="_blank">
@KesuikeTanabe 
Better use "https" to avoid security warning.

2020-12-22 02:52 UTC, DataSign-OTA commented
重複のためclose

2020-12-22 02:52 UTC, closed without merging